[versions]
kotlinGradlePlugin = "1.9.23"
arrow = "1.2.0"
kotlinx-datetime = "0.6.0-RC.2"
sqlite = "2.0.1"
[libraries]
arrow = { group = "io.arrow-kt", name = "arrow-core", version.ref = "arrow" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime"}
sqlite-driver = { group = "app.cash.sqldelight", name = "sqlite-driver", version.ref = "sqlite" }
[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinGradlePlugin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqlite"}