name: Release on Maven Central
on: 
  workflow_dispatch:
  push:
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+"
run-name: "Release Library ${{ github.ref_name }}"
jobs:
  build: 
    name: Build and bundle
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Push to local Maven repository
        env: 
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publishKastleLibPublicationToLocalRepoRepository
      - name: Zip local repository
        run: |
          cd ${{ github.workspace }}/maven-local
          zip -r kastle-lib.zip io -x "io/github/essay97/kastle-lib/maven-metadata*"
          pwd && ls -l
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-bundle
          path: ${{ github.workspace }}/maven-local/kastle-lib.zip
  deploy:
    name: Deploy bundle 
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Download artifact
        uses: actions/download-artifact@v4.1.7
        with: 
          name: maven-bundle
      - name: Get version number
        id: version-number
        run: |
          echo "VERSION=$(echo ${{ github.ref_name }} | sed 's/v//g')" >> "$GITHUB_OUTPUT"
      - name: Upload via Publisher API
        uses: fjogeleit/http-request-action@v1.15.5
        with:
          url: https://central.sonatype.com/api/v1/publisher/upload?publishingType=USER_MANAGED&name=io.github.essay97:kastle-lib:${{ steps.version-number.outputs.VERSION }}
          method: POST
          contentType: multipart/form-data
          files: '{ "bundle": "${{ github.workspace }}/kastle-lib.zip" }'
          bearerToken: ${{ secrets.PUBLISHER_API_BEARER }}
          
          
    
  
